### ISSUE TITLE
Feature request: multiple renderings

### ISSUE THREAD

**Issue by chrish42** [joerick/pyinstrument#100]
For the profiling workflow I'm creating, it would be super useful to be able to ask for multiple renderings of a report. For example, an HTML render to show to humans, and a JSON one for post-processing scripts to work from.

I'd be more than happy to do a pull request. The only thing that would need a bit of discussion beforehand is how to represent that in the command-line interface.

**Comment by joerick** [comment]
Sure! Would you need command line interface, or would the Python interface work?

**Comment by chrish42** [comment]
I know the Python interface only would be simpler, but I'd need the command-line interface too. At least, going from the first one to the second is mostly just figuring a good way to ask for multiple outputs & renderers with --arguments. Do you have an opinion for that, or do you want to propose something first and then we can discuss based on that? Either way, something that leaves the simple case of asking a for a single output type... simple.

**Comment by joerick** [comment]
Would saving a `pyireport` (a [ProfilerSession](https://github.com/joerick/pyinstrument/blob/master/pyinstrument/session.py#L9) object) work, instead? I'm thinking that it would be easier to save a single profiling session, then render it into `html` and `json` using `--load-prev` or similar later - perhaps `--load PATH`. The ipyreport is a lossless format, too, so the rendering options (e.g. `--timeline`) can be applied after the fact.

Otherwise, I guess we're looking at a command line interface like

    pyinstrument -r html -o profile.html -r json -o profile.json pythonscript.py

... which might be quite messy to document in `--help`, and to code.

**Comment by chrish42** [comment]
Sorry for the silence. Other priorities for a bit, then change of job recently, and it took me a while to get approvals for opensource contributions, etc., but now that that's all done, I'll be looking at this (and #97) when I have couple hours in between bigger tasks...

**Comment by chrish42** [comment]
I'll wait for #97 to be merged before working on that one. Just simpler, as both touch the argument parsing code.

**Comment by danvk** [comment]
I'm using this as a custom renderer:

```py
import json

from pyinstrument.renderers.base import Renderer

class IdentityRenderer(Renderer):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def render(self, session):
        return json.dumps(session.to_json())

    def default_processors(self):
        return []
```

With that in place, all we'd need is a way to pass a full path to `--load-prev`, right?

**Comment by danvk** [comment]
Actually, it looks like `--load-prev` already does support paths! So long as your file name ends with `.ipyreport`, you can pass an absolute path and it'll work:

```
$ ls -lh profile.pyireport
-rw-r--r--  1 danvk  staff   8.6M Jun 28 15:45 profile.pyireport
$ pyinstrument --load-prev=$(pwd)/profile -r html -o profile.html
```

**Comment by joerick** [comment]
Now possible in v4.2.0 using `pyinstrument -o session.pyisession myscript.py` to save and `pyinstrument --load session.pyisession` to load!
