### ISSUE TITLE
What are the dependencies?

### ISSUE THREAD

**Issue by CsatiZoltan** [joerick/pyinstrument#102]
What are the dependencies of *Pyinstrument*?

**Comment by joerick** [comment]
The only dependency is pyinstrument_cext, a C extension, also written by me. FYI you can normally find Python dependencies listed in `setup.py` - like this https://github.com/joerick/pyinstrument/blob/master/setup.py#L81

**Comment by CsatiZoltan** [comment]
Thanks. Yes, I always check setup.py, but this time I overlooked it.
On the other hand, when I wanted to install it through [conda](https://anaconda.org/conda-forge/pyinstrument) (I never want to risk of messing up my Python environment), I had incompatibility issues, which is strange as [*pyinstrument_cext*](https://github.com/joerick/pyinstrument_cext/blob/master/setup.py) does not mention any dependencies. Anyway, now that I am sure that it won't break other packages, I will simply install it with *pip*.
