### ISSUE TITLE
Profiling MPI programs and json outputs

### ISSUE THREAD

**Issue by ocnkr** [joerick/pyinstrument#108]
Hello,

Instead of using the command-line, is there a way to produce JSON output files using Python API like output_html() or output_text(), and is it possible to profile MPI programs that are written in Python? For example, is it possible to produce separate JSON output files for each process?  

Thank you.

**Comment by joerick** [comment]
I'm not familiar with MPI, but for sure it's possible to output JSON using the python API. You could do something like this:

```python
from pyinstrument import Profiler
from pyinstrument.renderers import JSONRenderer
profiler = Profiler()

profiler.start()
# do some work
profiler.stop()

print(JSONRenderer().render(profiler.last_session))
```
