### ISSUE TITLE
Feature request: open html in browser on context exit

### ISSUE THREAD

**Issue by ihincks** [joerick/pyinstrument#110]
I like to profile in jupyter notebooks, and have personally found this pattern useful:

```python
from pyinstrument import Profiler as _Profiler

class Profiler(_Profiler):
    def __exit__(self, *_, **__):
        super().__exit__(*_, **__)
        import tempfile
        import webbrowser            
        
        with tempfile.NamedTemporaryFile('w', delete=False, suffix='.html') as f:
            url = 'file://' + f.name
            f.write(self.output_html())
        webbrowser.open(url)
```

I am wondering about the possibility of adding this feature as an optional flag during the construction of `Profiler`?

**Comment by asmeurer** [comment]
Is this what you're looking for https://github.com/joerick/pyinstrument/pull/61?

**Comment by ihincks** [comment]
Thansk for pointing to that.

I'm looking specifically for the browser to open automatically when a profiler context exits because that is my (selfish) desired default behaviour. Feel free to close if this is not in line with the goals of the repo.

**Comment by asmeurer** [comment]
I see. I guess it could be a flag to Profiler. IMO it doesn't make sense for the Python API to open the browser by default. Although

```py
with Profiler(open_in_browser=True) as p:
    ...
```

wouldn't be much less typing than

```py
with Profiler() as p:
    ...
p.open_in_browser()
```

**Comment by asmeurer** [comment]
Then again, having only a single line that you have to add to a program (plus indenting some code) to profile it is simpler, so perhaps it is better to have the API work like that.

**Comment by ihincks** [comment]
What about a module level context like `html_profile`?

Along the lines of the following:
```
from contextlib import contextmanager

@contextmanager
def html_profile():
    profiler = Profiler()
    profiler.start()
    yield profiler
    profiler.stop()
    profiler.open_in_browser()
```

**Comment by joerick** [comment]
@asmeurer's snippet seems to solve this pretty well.

```
with Profiler() as p:
    ...
p.open_in_browser()
```
