### ISSUE TITLE
Constructors do not appear

### ISSUE THREAD

**Issue by amirouche** [joerick/pyinstrument#116]
I noticed that constructore do not appear.

It is prolly because there is not much callstack in most constructor. Is that correct?

**Comment by joerick** [comment]
Constructors should appear, yes. Probably you're not seeing it because not much time is spent there.  Try putting a `time.sleep(1)` in the constructor- you should see it then.

**Comment by amirouche** [comment]
Thanks. And thanks for this awesome project :100: :+1:
