### ISSUE TITLE
Where are the reports stored by default?

### ISSUE THREAD

**Issue by GittiHab** [joerick/pyinstrument#117]
Hi, maybe I am to blind to find the answer myself: where does `pyinstrument` store the reports by default? I.e., from where are they loaded, when using the `--load-prev` flag.

And since I am asking, is this what is changed when specifying `--outfile`?

Thanks :)

**Comment by joerick** [comment]
The save location is decided by [`appdirs`] - see here:
https://github.com/joerick/pyinstrument/blob/a8a90b653c041502df0af4558b687cde592c9ad7/pyinstrument/__main__.py#L244-L250

[`appdirs`]: https://pypi.org/project/appdirs/

`--outfile` will save the output to a file (like a .txt or a .html file), rather than printing to console or opening it in a browser.

**Comment by GittiHab** [comment]
Great thanks! Is there any plan to be able to specify an own path?

**Comment by joerick** [comment]
is there a particular reason `--outfile` doesn't work for you?

**Comment by GittiHab** [comment]
No, everything is fine. I was just curious, as I usually prefer to keep my files for one project together in the same directory. If the report is always stored in the users data directory it doesn't exactly support this goal. But this is really just a nice to have feature.

**Comment by joerick** [comment]
Ah, yes, gotcha. We could add a `PYINSTRUMENT_REPORTS_DIR` environment variable that would override the `reports_dir()` path. I guess setting `PYINSTRUMENT_REPORTS_DIR=""` would turn off the feature.

**Comment by GittiHab** [comment]
I guess this would be a solution. Being able to set a flag would be nicer, of course.

I will close this issue though as it is solved. Since it is your project, you can decide if you want to pick this up and add another issue. Maybe if I have time I will create a PR but I wouldn't count on it right now.
