### ISSUE TITLE
Would it be possible to show the class name in the results ?

### ISSUE THREAD

**Issue by altimore** [joerick/pyinstrument#118]
Hello, 

First many thanks for the work you put in this tool, it was the one i was dreaming of.

I'm using it to find bottlenecks in Django applications.

In this case i got multiple classes having a method called get_total(), would it be possible to display the class name to differentiate the different get_total() functions like Invoice.get_total(), InvoiceLine.get_total() or InvoiceQuerySet.get_total() in the results instead of just get_total.
It would be more convenient than having to check which is which in the source file during the reading.

Regards, 

Alti.

**Comment by joerick** [comment]
Yes, this would be really nice. It's not something that is naturally available via the [native Python `frame` interface](https://docs.python.org/3/library/inspect.html) but I think it's possible to 'guess' by looking at the type of an argument called `self` in the scope of the function. We'd have to be a little careful not to make it too slow, but I think there should be a way.

If you or somebody else is interested in working on a PR, the place to try adding it would be https://github.com/joerick/pyinstrument/blob/master/pyinstrument/profiler.py#L93, adding it to the first token in the identifier :)

**Comment by joerick** [comment]
This now works in v4.4.0!
