### ISSUE TITLE
timeline in interactive html view

### ISSUE THREAD

**Issue by startakovsky** [joerick/pyinstrument#119]
Hi! I love the timeline feature, it really helps me understand the order of operation and get my mind wrapped around execution flow. I get an error when using the `timeline=True` from inside any of the output / open functions except for text output. I guess if this is the place to put a feature request then this is it. I would be happy to submit a PR if it doesn't exist, but I'd want to know what level of effort you would you estimate for this.

**Comment by joerick** [comment]
You're right, that should be a fairly easy one. Please do send a PR if you have time!
