### ISSUE TITLE
Add a way to ignore modules in the output

### ISSUE THREAD

**Issue by ngoldbaum** [joerick/pyinstrument#12]
It would be nice if there were a way to only show contributions from certain modules. Right now I'm getting a lot of noise in my output from `nose` since I'm profiling a set of unit tests.  It would be nice if I could exclude traces that include `nose` and just see the timings for my code.

Perhaps this is me not understanding the purpose of the library - feel free to close if you don't agree that this is within the project scope.

**Comment by Tjorriemorrie** [comment]
I'm also very interested in this. Haven't looked into this, but was thinking that maybe a whitelist and blacklist of regex patterns, that matches on paths?
