### ISSUE TITLE
fastapi profiling

### ISSUE THREAD

**Issue by sandeeppilania** [joerick/pyinstrument#128]
I am new in using Profilers and working on a  Fastapi project and tried using your profiler as well as fastapi-profiler but in both as the cases i get only the framework level tracing, where in i need the tracing and timings for each of the internal methods call in order to find out which model in the pipeline is consuming the most of time. 
![image](https://user-images.githubusercontent.com/38011316/114238418-93255f00-9952-11eb-9129-a3f19e10621b.png)
Do i need to start profile on each project package in order to get details of all the methods, right now what i have tried is starting the profiler on fastapi api request and capturing it before sending the response.
Would really appreciate any help here.

**Comment by joerick** [comment]
If you want to show library frames, you'll need to supply the `show_all` argument to the HTML renderer. This argument can also be supplied to the `output_html` method, if you're using that.

**Comment by joerick** [comment]
Whoops, looks like you're using the text output. Still, the advice is the same, you want to set `show_all=True` when rendering the output.

**Comment by waqashameed** [comment]
@joerick it does not have an argument show_all

**Comment by joerick** [comment]
Here's the docs for the method with `show_all`: https://pyinstrument.readthedocs.io/en/latest/reference.html#pyinstrument.Profiler.output_text
