### ISSUE TITLE
assert root_frame is None from session.py

### ISSUE THREAD

**Issue by nealtaylor** [joerick/pyinstrument#129]
This is filed due to the request in the traceback:
  "File "/usr/local/lib/python3.9/site-packages/pyinstrument/session.py", line 77, in root_frame"
  "    assert root_frame is None, ASSERTION_MESSAGE"
  "AssertionError: Please raise an issue at http://github.com/pyinstrument/issues and let me know how you caused this error!"

This happened during closedown for 2 of 4 pyinstrument sessions each running configured variants of the same code initiated by subprocess.Popen's from a unittest class. Subprocesses had received SIGINTs but not yet exited.

This was the first instance. No attempt, yet, to reproduce or produce a minimal case.

Attached tar.gz includes code snippet showing invocation, log file, html results of the run, and the ~/Library/Application Support/pyinstrument/reports folder.

Please note that the URL in the assertion message is missing the "/joerick/" level.

OS X El Capitan version 10.11.6 (15G22010) - Intel (yes, ancient.)
Python 3.9.1 (default, Jan  4 2021, 14:52:36) 
[Clang 8.0.0 (clang-800.0.42.1)] on darwin

[pyinstrumentAssertOf20210430.tar.gz](https://github.com/joerick/pyinstrument/files/6407181/pyinstrumentAssertOf20210430.tar.gz)

**Comment by joerick** [comment]
I think this should be fixed in v4.0.0. Let me know if not!
