### ISSUE TITLE
Multiple root frame can exists with greenlet

### ISSUE THREAD

**Issue by schaumb** [joerick/pyinstrument#134]
[This statement](https://github.com/joerick/pyinstrument/blob/master/pyinstrument/session.py#L76) is false, because it can exists multiple root frame on same thread with thread switching techniques.

This code snippet fails:
```
import greenlet
import time


def y(oth):
    time.sleep(oth)

y(0.5)
greenlet.greenlet(y).switch(0.5)
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bela/.local/lib/python3.6/site-packages/pyinstrument/__main__.py", line 292, in <module>
    main()
  File "/home/bela/.local/lib/python3.6/site-packages/pyinstrument/__main__.py", line 214, in main
    f.write(renderer.render(session))
  File "/home/bela/.local/lib/python3.6/site-packages/pyinstrument/renderers/console.py", line 20, in render
    self.root_frame = self.preprocess(session.root_frame())
  File "/home/bela/.local/lib/python3.6/site-packages/pyinstrument/session.py", line 77, in root_frame
    assert root_frame is None, ASSERTION_MESSAGE
AssertionError: Please raise an issue at http://github.com/pyinstrument/issues and let me know how you caused this error!

```

**Comment by joerick** [comment]
Ahhh brilliant I've been looking for a minimal recreation of this bug for years! Thank you. I'll have a look at this in due course. 

By the way, if you have a pressing need, it might be fixed by #126, so you might try that. Let me know what happens, I'd be curious.

**Comment by schaumb** [comment]
The fix solves the error, but the greenlet stack `sleep` function was recognized as a `0.501 [await]`

```
> python3.8 -m pyinstrument gl.py 

  _     ._   __/__   _ _  _  _ _/_   Recorded: 15:42:51  Samples:  2
 /_//_/// /_\ / //_// / //_'/ //     Duration: 1.003     CPU time: 0.001
/   _/                      v3.4.2

Program: gl.py

1.002 MainThread  <thread>:139837333137216
├─ 0.501 _run_module_as_main  runpy.py:167
│     [8 frames hidden]  runpy, pyinstrument, <string>
│        0.501 _run_code  runpy.py:62
│        └─ 0.501 <module>  gl.py:1
│           └─ 0.501 y  gl.py:5
│              └─ 0.501 sleep  <built-in>:0
│                    [2 frames hidden]  <built-in>
└─ 0.501 y  gl.py:5
   └─ 0.501 [await]  

To view this report with different options, run:
    pyinstrument --load-prev 2021-06-23T15-42-51 [options]
```

**Comment by joerick** [comment]
Interesting, thanks. I'll have to dig into the internals of greenlet to find out why.

**Comment by schaumb** [comment]
I made a hack for testing reason (and because of using python3.6, where the PR fails to install):
```
<                        # There should only be one root frame, as far as I know
<                        assert root_frame is None, ASSERTION_MESSAGE
<                        root_frame = frame
------------
>                        if root_frame is None:
>                            root_frame = frame
>                        else:
>                            root_frame.add_child(frame)
```

This prints the following:

```
> python3 -m pyinstrument gl.py 

  _     ._   __/__   _ _  _  _ _/_   Recorded: 15:54:30  Samples:  2
 /_//_/// /_\ / //_// / //_'/ //     Duration: 1.002     CPU time: 0.001
/   _/                      v3.4.2

Program: gl.py

1.002 _run_module_as_main  runpy.py:167
├─ 0.501 _run_code  runpy.py:62
│     [7 frames hidden]  runpy, pyinstrument, <string>
│        0.501 _run_code  runpy.py:62
│        └─ 0.501 <module>  gl.py:1
│           └─ 0.501 y  gl.py:5
│              └─ 0.501 sleep  <built-in>:0
│                    [2 frames hidden]  <built-in>
└─ 0.501 y  gl.py:5
   └─ 0.501 sleep  <built-in>:0
         [2 frames hidden]  <built-in>

To view this report with different options, run:
    pyinstrument --load-prev 2021-06-23T15-54-30 [options]
```

So probably the **frame information are there**, but the printed information was translated to `[await]`

**Comment by joerick** [comment]
Cool, yes that makes sense. On #126 I'm using the 'contextvar' module to separate async contexts on the same thread. What's interesting about greenlet as compared to async/await is that it doesn't seem to inherit the context of whatever started it. I suppose it's more like a thread that way. So to pyinstrument it looks like suddenly execution is happening in a different async task, so it assumes something must have awaited. Anyway. Probably this means that profiling with greenlet won't really benefit from the async support in #126, and I should provide a way to turn it off, while keeping the flexibility around multiple root frames etc.

**Comment by schaumb** [comment]
greenlets stores information about their [frames](https://greenlet.readthedocs.io/en/latest/api.html#greenlet.greenlet.gr_frame), but the context switch can come from any other greenlet. It has an [API](https://greenlet.readthedocs.io/en/latest/tracing.html) for tracing the switches. With that it can join frame to its caller frame.
