### ISSUE TITLE
feature request: dump and analyze

### ISSUE THREAD

**Issue by codelol** [joerick/pyinstrument#14]
It is cool to print beautiful callstacks after we stop the profiler and call output_text/html. However, this only gives users one angle to look at data: full-depth (the whole callstack is printed) and caller-based (caller are parents, and callee functions are children on the tree).

In many cases, it is useful if we can analyze the same profiling data from different angles. For example:

(1) callee-based: for development in a big software framework, new functions are part of the framework, and are often at the bottom or at most in the middle of the call stack. If the profiler can only print callstack as caller-based, it would take a lot of time to find the data people care about.

(2) reduced callstack depth:if I only want a big picture, I may want to filter the results with an option like "depth=1" or "depth=2" etc, to print only functions at the top or bottom of the callstack. This option should work in either caller-based or callee-based 
stack. I know in web UI, the stack tree and fold and expand so it doesn't have to be changed, but the text mode doesn't have this option, and if we want to generate reports, we need to process text output.

In order to do this, we might want to separate result display into two steps. Step1: dump the data. Step 2: process the data.

Step 1 conceptually works as it does now: when profiler is stopped, it "dump" profiling data into a user specified or default file name.

Step 2: this requires a new tool that can understand the dump and display callstacks as a user desires.

So the point is to give users more angles to analyze without having to profile the same application multiple times.

Any thoughts?

**Comment by anntzer** [comment]
A nice dump format to support may be callgrind, for which many specialized and good GUI viewers are already available (e.g. https://kcachegrind.github.io/html/Home.html, http://www.profilingviewer.com/).
(IMHO this is right now the killer feature of the pprofile profiler, https://github.com/vpelletier/pprofile).

**Comment by joerick** [comment]
Following the [Renderer](https://github.com/joerick/pyinstrument/blob/v2.0.0/pyinstrument/renderers.py) abstraction in v2.0, this is now possible. I think it should be possible to create a JSON renderer, or a callgrind renderer using a `Renderer` subclass. Would love to see PRs to that effect!

**Comment by joerick** [comment]
@drd just revisiting this thread years later - on the off-chance you're still interested check out the new timeline support - it doesn't aggregate frames so would produce more useful flame-charts.
