### ISSUE TITLE
Pyinstrument doesn't work for me

### ISSUE THREAD

**Issue by KexoTV** [joerick/pyinstrument#162]
Hi, i tried your module but it isn't outputting anything, i am not sure if i did it right:
![image](https://user-images.githubusercontent.com/55331891/139557383-b7064fa7-0b10-4d9b-8e30-f8e9fbb6f07e.png)
So i tried second option to put profiler into my code but it didn't do anything aswell

Python 3.10.0
Windows 10 Home
Pyinstrument 4.0.4

**Comment by joerick** [comment]
What does your program look like? Anything unusual about it?

**Comment by KexoTV** [comment]
> What does your program look like? Anything unusual about it?

it's discord bot made in python so it should be normal

**Comment by joerick** [comment]
perhaps you could post some code that shows it not working.

**Comment by KexoTV** [comment]
just found out it might be because the python script never stops -  bots have to be active all the time
i tested pyinstrument on passive python script and it worked

**Comment by joerick** [comment]
Hitting Ctrl-C to stop the program should still print the profile output - does it not do that for you?

**Comment by KexoTV** [comment]
yes it worked now thanks, i had to press it 3 times
