### ISSUE TITLE
How to use Pyinstrument with django rest framework running in Django?

### ISSUE THREAD

**Issue by magedhelmy1** [joerick/pyinstrument#165]
I am not sure how to use it with Django, django rest framework and Docker. The user guide was not clear to me.

Django is running in docker, and I can see pyinstrument is installed fine

Now I want to pyinstrument this post query to see what takes the longest time. 

        self.client.post("api/cars/", data=
        {
            "model": 1
        })

How can I see the results of Pyinstrument when executing the above URL for example?

**Comment by joerick** [comment]
For Django APIs, your best bet is the PYINSTRUMENT_PROFILE_DIR option, in the Django extension. https://pyinstrument.readthedocs.io/en/latest/guide.html#profile-a-web-request-in-django .

That will write out a profile for every request, that you can review after the fact.

I haven't worked in Django for a while, but it might also be the case that you could use the Django test client to run the views directly, in which case, you could try wrapping the [above snippet in a profiler](https://pyinstrument.readthedocs.io/en/latest/guide.html#profile-a-specific-chunk-of-code) using the Python API.
