### ISSUE TITLE
What are the [self] items?

### ISSUE THREAD

**Issue by Gabriel-p** [joerick/pyinstrument#167]
I'm getting a lot of `[self]` items in my profile:

![Captura de pantalla de 2021-11-20 10-57-03](https://user-images.githubusercontent.com/6054951/142728966-ceee74ed-b111-4e1e-ba67-c2ef632bcd05.png)

These are mainly at the top, ie using the most resources. What do these represent exactly?

**Comment by joerick** [comment]
This just means that time was spent inside that function itself, rather than any children of it.

**Comment by Gabriel-p** [comment]
Of course. Thank you!
