### ISSUE TITLE
Feature request: cumulated time / total time / ncalls statistics + report

### ISSUE THREAD

**Issue by loehnertj** [joerick/pyinstrument#168]
I used pyinstrument today to find bottlenecks in my optical simulation code, and found it overall very helpful. The HTML report is very usable and looks great!

One feature I was missing (or didn't find :-)) compared to builtin cProfile, is the possibility to sort / display **cumulative time for individual functions**. I.e. total time spent in that function, regardless of the call stack above. This is really crucial to find "hot" functions, i.e. with short runtime but high call count.

In the simplest form, the HTML report could show this as on-hover popup; or make it more fancy and display a sorted list grouped by module / function...

If this already possible, I'd appreciate a pointer on how to...

**Comment by joerick** [comment]
Hey @loehnertj ! Thanks for the comment.

My opinion is that cProfile already does this, part of pyinstrument's differentiation is that the tree is (normally) important.

Having said that, it's possible that this might come as a side-effect of line-profiling support. I'm not considering it a goal by itself though.

**Comment by joerick** [comment]
If you have ideas on how it would be different to cProfile, I'm happy to discuss!

**Comment by loehnertj** [comment]
You are fully right that cProfile can do this. It's just that it would be nice to have it all in one tool, with the option to switch between views with a mouseclick. Also, the HTML report is very nice and allows interactive exploration, collapsing/expanding and filtering. cProfiler OTOH gives you a wall of text. Sure you can import data into 3rd party tools, but this gets tedious when iterating lots of test runs.

At least for my typical use cases :-), this would be the one missing feature to make pyinstrument my one-stop favorite profiler. But I understand that it might be a lot of work and maybe doesn't fit into the greater concept. So, take it as you like. :-)

**Comment by joerick** [comment]
Yeah, I can kinda imagine a tabbed interface in the HTML report, where there's the top-down tree report, or alternatively a 'functions' view where functions could be filtered to just app code, or searched. (And then from there, you could jump into a line profile for each of those.)

I'm still trying to figure out how to do that at the moment. I've got this annoying situation where half the data processing lives in Python and some others live in Javascript. Wish I could unify that somehow...
