### ISSUE TITLE
Replace times with percentage?

### ISSUE THREAD

**Issue by willmcgugan** [joerick/pyinstrument#171]
Thanks for this project. I've found it really easy to use and I love the output.

Would it be possible to show the times as a percentage of the total runtime rather than in seconds? I would find that a more useful metric generally. Perhaps it could be enabled with a command line switch?

**Comment by joerick** [comment]
Hi @willmcgugan ! Thanks for the kind words :)

I guess you're talking about the Console renderer? Yes I think we could add at to the output, under a renderer option / command line switch. Perhaps it's time to generalise the renderer options interface on the command line, too. I'll have a think about this.

**Comment by joerick** [comment]
Now possible by doing `pyinstrument -p time=percent_of_total`!
