### ISSUE TITLE
This project is grand. 

### ISSUE THREAD

**Issue by koaning** [joerick/pyinstrument#173]
Honestly, the developer experience is so nice that I immediately felt compelled to make a quick video course on it [here](https://calmcode.io/pyinstrument/introduction.html). 

Just wanted to demonstrate my appreciation. Well done! This is a really nice project.

**Comment by joerick** [comment]
Wow, these videos are great!!! I'm very happy that you find the project fun to work with. And thank you for dropping by to let me know!

I might link to these from the docs somewhere, if that's okay with you? They're a great introduction to the abilities of pyinstrument, and then they go deeper.

By the way, did you notice any sharp edges while recording that would be worth me looking at?

**Comment by koaning** [comment]
Happy to hear you like it. 

Feel free to link to the content from the docs! I write tutorials for a bunch of projects that I like and the inbound links from projects make it an easy-to-discover resource. 

In terms of sharp edges, the final video gives a sharp edge that's related to profilers in general. I'm currently using it to try to find expensive bits of code in pytest and I've noticed that [recurion can be things tricky](https://twitter.com/fishnets88/status/1472154785918902277?s=20). I might be able to explore this further by doing a trick similar to [pytest-duration-insights](https://github.com/koaning/pytest-duration-insights). 

I suppose I've yet to try out to use it in combination with Tensorflow/Cython/Numpy stuff ... there may be some odd things there, but in general ... the main thing I *really* enjoy here is just the pragmatism of the tool. It just works, looks nice and it's simple to use.
