### ISSUE TITLE
Expand [self] entries 

### ISSUE THREAD

**Issue by nonamethanks** [joerick/pyinstrument#175]
In my case I have a pretty complex application, and as you can see from the following screenshot most of the time is spent inside certain methods:
![image](https://user-images.githubusercontent.com/12946050/148522561-fc993435-7aff-4587-a892-782dcf52271c.png)
I assume the [self] entries are anything inside a method that does not call another method. Is there no way to expand these?

**Comment by joerick** [comment]
Unfortunately no, pyinstrument only knows about function calls. You might have some more luck with [line_profiler](https://pypi.org/project/line-profiler/).
