### ISSUE TITLE
time parser readability is poor in asyncio

### ISSUE THREAD

**Issue by yangjinhao1234** [joerick/pyinstrument#178]
I want use this package to check my code in async mode.
So I add this time parser into my code. Then run the test code.
But I found this result
20.872 <module>  new_batch_main.py:9
└─ 20.872 run_until_complete  asyncio/base_events.py:573
      [8 frames hidden]  asyncio, selectors, <built-in>
         20.212 epoll.poll  <built-in>:0
         0.659 _run  asyncio/events.py:79

There are many async func in my code. But the parser like can't catch every async func .
package version is 4.1.1   
python version 3.8.0
I don't set the arg  "async_mode"  of Profiler.
 could u help me and give my some advice?

**Comment by joerick** [comment]
Hey @yangjinhao1234 , could you share the code that you're using the invoke the profiler? And where it sits in relation to the async work that you're doing?

**Comment by yangjinhao1234** [comment]
@joerick  
sorry, I can't share complete code . But it like this:

profiler=Profiler()

async def func1():
    profiler.start()
    
    """
    	many async func
    """
    
    profiler.stop()
    profiler.print()

if __name__=="__main__":
    loop=asyncio.get_event_loop()
    loop.run_until_complete(func1())
    
  async func run in the asyncio loop. I like to do this for the test.

**Comment by yangjinhao1234** [comment]
@joerick  
sorry my brother. I think  the mass virtual  envs make this trouble.  parser work well on my colleague. It's working fine now when I reinstall the package. 
thanks for ur fast reply. It's a crazy project. I will try my best to contribute code.
really thank u.
