### ISSUE TITLE
Python 3.11 compatibility

### ISSUE THREAD

**Issue by adriangb** [joerick/pyinstrument#187]
I have a project that uses pyinstrument as a dev dependency and it's failing to build on Python 3.11: https://github.com/adriangb/di/runs/6377204976?check_suite_focus=true#step:5:156

I can confirm this also happens locally with a simple `pip install pyinstrument` on 3.11.

**Comment by tonybaloney** [comment]
I'll see if I can raise a PR today or tommorrow
