### ISSUE TITLE
Profiling pytest tests

### ISSUE THREAD

**Issue by felixriese** [joerick/pyinstrument#188]
I just figured out that `pyinstrument` also works well with `pytest` tests, really nice!

Should we add this to the documentation?
(If this is wanted, I can try to make a PR)

```bash
pyinstrument -m pytest test.py
```

**Comment by joerick** [comment]
Yeah! Send over a PR :)

**Comment by felixriese** [comment]
@joerick I added the PR #195 :)
(no idea if I needed a fork for that. hope that works for you)

**Comment by joerick** [comment]
Fixed in #193. Thank you for the suggestion!
