### ISSUE TITLE
Proposal: Optionally Skip Frames in Output

### ISSUE THREAD

**Issue by mlucool** [joerick/pyinstrument#190]
Hi,

`__tracebackhide__` is used in [pytest](https://doc.pytest.org/en/latest/example/simple.html#writing-well-integrated-assertion-helpers) and [IPython ](https://github.com/ipython/ipython/pull/12359)to tell tooling that a frame should be hidden from the user when looking at stacktraces. It would be helpful if users can optionally reuse this marking to tell pyinstrument not to show it in output. This is generally helpful as it enables you focus on user code you can control instead of library code that you cannot.

Example:
```
0.100 A
    |- 0.090 B
         |- 0.080 C
               | - 0.070 D
```

If B and C are hidden, we'd show:
```
0.100 A
   |- <skipped 2 frames>
       |- 0.070 D
```

**Comment by joerick** [comment]
Interesting. So if this local is set tooling should ignore these frames? It will require some refactorings and might have a perf impact but looks like a good idea!

**Comment by mlucool** [comment]
Exactly!

**Comment by mlucool** [comment]
Is this something you want to tackle or would you prefer someone makes a PR with this feature for you to review?

**Comment by joerick** [comment]
Happy to review a PR on this, if you want to have a crack at it! Though it might require modifications to the C extension, i don't know if you'd be comfortable with that?

**Comment by telamonian** [comment]
@joerick I took this one on. See #211. Feedback would be much appreciated
