### ISSUE TITLE
ModuleNotFoundError: No module named 'pyinstrument.low_level.stat_profile'

### ISSUE THREAD

**Issue by wjunneng** [joerick/pyinstrument#205]
version：pyinstrument 4.2.0 pypi_0 pypi
                Python 3.7.13 

from pyinstrument import Profiler
profiler = Profiler()
profiler.start()
...
profiler.stop()
profiler.print()

raise ModuleNotFoundError: No module named 'pyinstrument.low_level.stat_profile'

**Comment by wjunneng** [comment]
try: 
conda install -c conda-forge conda-forge::pyinstrument

success!!!

**Comment by joerick** [comment]
How were you installing pyinstrument to get the above error?

That module is compiled, so it seems like the compilation step was missing in however you installed it.

**Comment by WMRamadan** [comment]
> try: conda install -c conda-forge conda-forge::pyinstrument
> 
> success!!!

@wjunneng Does this mean you solved this issue?

**Comment by joerick** [comment]
Closed, feel free to reopen if there's still an issue.
