### ISSUE TITLE
Python compiled extensions sampling with the gdb 7+ Python extensions

### ISSUE THREAD

**Issue by ogrisel** [joerick/pyinstrument#22]
`gdb` makes it possible to get the backtrace of C programs with the `bt` command and since version 7, when the program is a Python program it's also possible to get the Python level call stack using the `py-bt` command, for instance see this post:

http://misspent.wordpress.com/2012/03/24/debugging-cc-and-cpython-using-gdb-7s-new-python-extension-support/

So it might be possible to use that to collect mixed Python + C call stacks every 10ms or so to profile inner call to C compiled extensions (e.g. Cython code) in a Python program when `gdb` is available on the system.

Also [Pyrasite](http://pyrasite.com/) is using `gdb` to inject arbitrary Python code in a running Python process so it might also be possible to use a similar approach to attach the `pyinstrument` profiler to an existing running Python process.

**Comment by joerick** [comment]
Despite this being an interesting idea, maybe it's one for another project! I'm pretty set on the profiling method for now.
