### ISSUE TITLE
numpy.core.dtype fails to initialize in a pytest session

### ISSUE THREAD

**Issue by rth** [joerick/pyinstrument#228]
I have somewhat curious issue I run into. I'm trying to run pyinstrument with pytest on some test file,
```
pyinstrument -m pytest some_test_file.py
```
Without pyinstrument the test passes fine. If I add pyinstrument, the test fails, because apparently `numpy.core.dtype` is then None instead the expected type constructor. 

What we should get,
```py
>>> from numpy.core import numeric
>>> numeric.dtype
<class 'numpy.dtype'>
```
what I'm getting if I run the above pytest session with `--pdb`
```py
(Pdb) from numpy.core import numeric
(Pdb) print(numeric.dtype)
None
```
At the same time running the equivalent code with pyinstrument  without pytest works fine. I cannot produce a minimal working example so far. As just using numpy with a synthetic test and pyinstrument + pytest also works fine. Maybe also due to some interaction with plotly.

Anyway, I don't have much hope that it's solvable from the provided information (and I cannot share the non public code that makes this error). Mostly opened in case anyone else stumbles on something similar.

**Full error traceback**

The actual error happens [here in numpy](https://github.com/numpy/numpy/blob/main/numpy/core/getlimits.py#L653) and makes sense is `numpy.core.numeric.dtype is None`
```
..\..\mambaforge\envs\conda-prod\lib\site-packages\numpy\core\getlimits.py:650: in __init__
    self.dtype = numeric.dtype(int_type)
E   TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:
..\<module-name-redacted>:12: in <module>
    import plotly.express as px
..\..\mambaforge\envs\conda-prod\lib\site-packages\plotly\express\__init__.py:15: in <module>
    from ._imshow import imshow
..\..\mambaforge\envs\conda-prod\lib\site-packages\plotly\express\_imshow.py:4: in <module>
    from .imshow_utils import rescale_intensity, _integer_ranges, _integer_types
..\..\mambaforge\envs\conda-prod\lib\site-packages\plotly\express\imshow_utils.py:21: in <module>
    _integer_ranges = {t: (np.iinfo(t).min, np.iinfo(t).max) for t in _integer_types}
..\..\mambaforge\envs\conda-prod\lib\site-packages\plotly\express\imshow_utils.py:21: in <dictcomp>
    _integer_ranges = {t: (np.iinfo(t).min, np.iinfo(t).max) for t in _integer_types}
..\..\mambaforge\envs\conda-prod\lib\site-packages\numpy\core\getlimits.py:652: in __init__
    self.dtype = numeric.dtype(type(int_type))
E   TypeError: 'NoneType' object is not callable
```

**Comment by rth** [comment]
Sorry clicked on the submit button by accident before the description was ready. Edited the description above.

**Comment by rth** [comment]
Looks like it's a duplicate of https://github.com/numpy/numpy/issues/21519 and the fix is to update pandas. Anyway really curious issues.

**Comment by joerick** [comment]
thanks for the report. A very curious issue! I can say that the commonality between pyinstrument is use of the `sys.setprofile`/`sys.settrace` functions, it's possible that something in the interpreter is sensitive to this. Very odd.
