### ISSUE TITLE
Can Pyinstrument get a precollected `.pstats` input and renders it as html?

### ISSUE THREAD

**Issue by 4l1fe** [joerick/pyinstrument#245]
I'd like to reuse `.pstats` file that are from other sources.

**Comment by joerick** [comment]
Unfortunately no, the pstats file doesn't contain enough information to render a full call stack like pyinstrument does. You might check out snakeviz, that tool has some good-looking visualisations from pstats

**Comment by 4l1fe** [comment]
Thank you
-------- Original Message --------
