### ISSUE TITLE
Thread support in signal mode

### ISSUE THREAD

**Issue by mgedmin** [joerick/pyinstrument#26]
Your README says 

> On Mac/Linux/Unix, pyinstrument can run in 'signal' mode. [...] However, this can only profile the main thread.

You could instead sample the call stacks of all active threads by using [sys._current_frames()](https://docs.python.org/3/library/sys.html#sys._current_frames), which returns a dict mapping thread IDs to frame objects.

**Comment by joerick** [comment]
Thanks mgedmin! However this is no longer a problem in v2.0 since we switched to the C-extension API. However, pyinstrument still must be started and stopped in the thread you wish to profile.
