### ISSUE TITLE
Feature Request: Render stack as collapsed in HTML

### ISSUE THREAD

**Issue by izagorac** [joerick/pyinstrument#320]

**Comment by izagorac** [comment]
Would it be possible to add the option that the HTML gets rendered as collapsed instead of expanded? Currently if I want to get an overview of the function calls that take up most time I first need to collapse them by hand.

**Comment by joerick** [comment]
The convention here, for treeviews, is to hold the option key while closing the highest-level item. That should collapse the whole tree. That isn't implemented yet but I'd prefer that over adding a render option.

**Comment by izagorac** [comment]
That ofcourse also works, curious to see whether it can be implemented
