### ISSUE TITLE
Vertical scroll in HTML output

### ISSUE THREAD

**Issue by joouha** [joerick/pyinstrument#346]
In the timeline view of the HTML output, I often have call stacks which extend off the bottom of the page and cannot be viewed. It it possible to add a vertical scroll bar?

Thanks for the awesome tool!

**Comment by joerick** [comment]
You can click and drag to pan around! Maybe I should add a hint for that somewhere.

**Comment by joouha** [comment]
Thanks that's perfect! I didn't even think to try that.
