### ISSUE TITLE
Add a way to screen out importlib noise

### ISSUE THREAD

**Issue by ngoldbaum** [joerick/pyinstrument#35]
I often use pyinstrument to profile importing a module to figure out ways to speed up imports. On python2 this works very nice but on python3 pyinstrument will pick up frames from importlib, making it much harder to visually see what's happening in the pyinstrument profile. This is happening because importlib was rewritten from C to python in python3, so pyinstrument is able to capture stack frames from it in python3.

To make that concrete, here's the profile for "import sympy" generated under python2:

https://gist.github.com/ngoldbaum/3e2f5213b45a64f67167d0dbd5878ad5

and python3:

https://gist.github.com/ngoldbaum/fb46b92f22a65181aa7442e2af2f51c1

**Comment by joerick** [comment]
Hey @ngoldbaum! Been a little while but I had a chance to pay down some technical debt in the project and fix this today. There's a fix on the master branch - you can try it out by doing `pip install https://github.com/joerick/pyinstrument/archive/master.zip`

If you get a chance please give a shot and let me know what you think!

**Comment by ngoldbaum** [comment]
> Importlib frames are removed - you won't see them at all. Their children are retained, so imports are just transparent.

Woohoo!
