### ISSUE TITLE
Version 2.0.1 can't import the top level package.

### ISSUE THREAD

**Issue by moorepants** [joerick/pyinstrument#37]
See: 

```
moorepants@garuda:pyinstrument((v2.0.1))$ python -c "import pyinstrument"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/moorepants/src/pyinstrument/pyinstrument/__init__.py", line 1, in <module>
    from pyinstrument.profiler import Profiler
  File "/home/moorepants/src/pyinstrument/pyinstrument/profiler.py", line 8, in <module>
    from pyinstrument_cext import setstatprofile
ImportError: No module named 'pyinstrument_cext'
```

Note that this was picked up on the conda-forge build: https://github.com/conda-forge/pyinstrument-feedstock/pull/6

**Comment by joerick** [comment]
Hey. Looks like you're missing a dependency - `pyinstrument_cext` is a separate package that contains the C extension used by `pyinstrument`. It's on PyPI and listed as a dependency in `setup.py`.

**Comment by moorepants** [comment]
Thanks. We need to make a conda forge package for the new dependency.
