### ISSUE TITLE
How can i use it in windows?

### ISSUE THREAD

**Issue by owandywang** [joerick/pyinstrument#39]

**Comment by movermeyer** [comment]
[Same as on Linux](https://github.com/joerick/pyinstrument/blob/master/README.md). 
No difference.

**Comment by joerick** [comment]
Hey owandywang

cibuildwheel is designed to run on a CI service, we support Appveyor for building Windows wheels. Please see the readme for instructions on how to set up.

**Comment by joerick** [comment]
Apologies, I got my repositories mixed up! Regardless, Pyinstrument works on Windows just as it does on Mac/Linux. Check the readme for instructions.
