### ISSUE TITLE
Continuous segfaults

### ISSUE THREAD

**Issue by jredrejo** [joerick/pyinstrument#40]
I am trying to use pyinstrument in a Django project and it's segfaulting in almost every page. In this case, every page is the html itself plus some API requests that are done from the page JavaScript to the same Django server. 
I have managed to solve it adding a filter that allows me to profile only one of the requests. The code for the filter is in this commit: https://github.com/jredrejo/pyinstrument/commit/004a66ca1c363d1f421a4a6d5f968617e699afb3

The project I am profiling is https://github.com/learningequality/kolibri . I added the middleware setup at 
https://github.com/learningequality/kolibri/blob/develop/kolibri/deployment/default/settings/base.py

The problem happens whenever PYINSTRUMENT_PROFILE_DIR  is set, I need it to profile the api requests.

**Comment by joerick** [comment]
Wow, interesting! Perhaps we could be seeing some thread danger in `pyinstrument_cext`? Are you able to provide a more minimal example or some instructions to recreating in your repo?

**Comment by jredrejo** [comment]
Sure, as I commented in my previous message, I was trying to profile kolibri, http://kolibri-dev.readthedocs.io/en/develop/start/getting_started.html#setting-up-kolibri-for-development contains all the instructions to do the testing. I added the pyinstrument setup in the file https://github.com/learningequality/kolibri/blob/develop/kolibri/deployment/default/settings/base.py

**Comment by joerick** [comment]
Started to work on a fix for this over at https://github.com/joerick/pyinstrument_cext/pull/3

**Comment by joerick** [comment]
Hi @jredrejo, this should be fixed in the latest version, v2.0.4. Let me know if it works for you!

**Comment by jredrejo** [comment]
Thanks very much. Yes, upgrading pyinstrument_cext to 0.2.0 solves the problem!!
