### ISSUE TITLE
Running modules

### ISSUE THREAD

**Issue by iddan** [joerick/pyinstrument#43]
I'd like to trace a program requiring execution with `python -m`. How should I do it? I know Python 3.7 has introduced support for it in some of the script executing modules.

**Comment by joerick** [comment]
Here's the commit that added it to cProfile: https://github.com/python/cpython/commit/7973e279a21999f134aff92dd6d344ec4591fae9

Nothing clever, just adding another option to the command line parser. PRs welcome!
