### ISSUE TITLE
Feature Request: JSON Renderer

### ISSUE THREAD

**Issue by iddan** [joerick/pyinstrument#44]
Hey, I've seen on pervious discussion an idea mentioned to implement a JSON renderer.
How hard should it be?
How familiar should I be with the code base and underlying concepts to implement it?
Is it a desired feature in the library?
Awesome work

**Comment by iddan** [comment]
I want to implement an interactive GUI with [React Flame Graph](https://react-flame-graph.now.sh/) (Which was open sourced very lately after I asked in intention to create interactive Python flame graphs)

**Comment by joerick** [comment]
Hmm! That's a good find! So you're outputting JSON in a specific format for this React component. In that case, it's probably not something that would be added to this project. If you were able to make another HTMLRenderer that output these charts, that could be pretty useful though!

pyinstrument supports a dotted path to a Renderer class, so you could develop your renderer in a separate module and run it using something like `pyinstrument --renderer=pyi_react_flame.Renderer myscript.py`

**Comment by iddan** [comment]
I don't want to implement a renderer currently. Just to get a JSON I'll provide to the React app.

**Comment by iddan** [comment]
Implemented at #46 . The interface is generic: I'm aiming to translate it to the React Flame Chart in a separate app.
