### ISSUE TITLE
Cannot import Profile (DLL failed)

### ISSUE THREAD

**Issue by Tjorriemorrie** [joerick/pyinstrument#48]
Getting following stacktrace running python2:
```
  File "C:\xplanbase\version\99.99.999\src\py\xpt\resourceful\api\portfolio\modelling.py", line 571, in __call__
    from pyinstrument import Profiler
  File "C:\Python27\lib\site-packages\pyinstrument\__init__.py", line 1, in <module>
    from pyinstrument.profiler import Profiler
  File "C:\Python27\lib\site-packages\pyinstrument\profiler.py", line 8, in <module>
    from pyinstrument_cext import setstatprofile
ImportError: DLL load failed: The specified module could not be found.
```
I have
pyinstrument==2.1.1
pyinstrument-cext==0.2.0

**Comment by joerick** [comment]
Thanks for the report. I can't test on Windows at the moment, but the pyinstrument_cext wheels are tested in CI on windows, so work in some cases, as far as I'm aware. Anything unusual about your machine/setup that might affect this?

**Comment by Tjorriemorrie** [comment]
It's setup for work, so many things going on ;)
I'll have to pull cest and try to debug it locally to find it then.
I don't know c unfortunately, how do I run the tests?

**Comment by joerick** [comment]
`python setup.py test` should do the trick

**Comment by Tjorriemorrie** [comment]
That works fine. I did however uninstall pyinstrument_cext and then ran
`python setup.py install` and now it works.
