### ISSUE TITLE
--html producing terminal output

### ISSUE THREAD

**Issue by asmeurer** [joerick/pyinstrument#53]
I am using 

```
python -m pyinstrument --html -o test.html test.py
```

`test.html` contains the terminal formatted output, not the HTML.

**Comment by asmeurer** [comment]
By the way, I suggest switching to argparse. It handles argument parsing better.

**Comment by joerick** [comment]
Yikes! Did you get a chance to see why that might happen? Does --html swallow the next arg?

**Comment by asmeurer** [comment]
Looks like it is already fixed in master c9ca93716898faa244efee5b6c05dda6156f30ab. Can you do a release?

**Comment by asmeurer** [comment]
By the way, it would be useful to have a `--version` flag to the command line.

**Comment by joerick** [comment]
Sure, apologies for the delay in the release, I've been getting carried away with work on the next major version! I'll do one now.

> By the way, it would be useful to have a --version flag to the command line. 

Good idea, i'll see if I can get that in the next release.

**Comment by joerick** [comment]
Released as v2.3.0!
