### ISSUE TITLE
Renderer doesn't work.

### ISSUE THREAD

**Issue by joylin1984** [joerick/pyinstrument#54]
tested on windows10, python3.6.6 pyinstrument2.30

"--html, -r json, -r html " doesn't work.

And， --output file doesn't work either.

**Comment by joylin1984** [comment]
Hi, joe. Thanks for answer. I get no errors.

**Comment by joerick** [comment]
So you get no output at all? Could you post the exact command you're running it with?

**Comment by joylin1984** [comment]
```python
 pyinstrument qa_test.py --html
<class 'PyQt5.QtGui.QIcon'>
4.418 <module>  qa_test.py:4
└─ 4.380 main  qa_test.py:106
   ├─ 2.152 pixmap  qtawesome\iconic_font.py:150
   │  └─ 2.122 paint  qtawesome\iconic_font.py:146
   │     └─ 2.122 paint  qtawesome\iconic_font.py:70
   │        └─ 2.122 _paint_icon  qtawesome\iconic_font.py:75
   └─ 0.220 __init__  qa_test.py:16
```

**Comment by joerick** [comment]
Could you try `pyinstrument --html qa_test.py`?

**Comment by joylin1984** [comment]
Yes，it's working. Because of my carelessness, I got the orders wrong！thanks for your answer！

**Comment by joerick** [comment]
no problem :)
