### ISSUE TITLE
error in pypy

### ISSUE THREAD

**Issue by Kyle-Kyle** [joerick/pyinstrument#55]
I got this error when trying to profile a script using pyinstrument in pypy
~~~
ImportError: /home/xxxxxxx/.virtualenvs/pypy/site-packages/pyinstrument_cext.pypy3-60-x86_64-linux-gnu.so: undefined symbol: PyFrame_LocalsToFast
~~~

**Comment by joerick** [comment]
Hey Kyle, we only support CPython at the moment, unfortunately. That being said, if pypy supports sys.setprofile or a similar C interface we could perhaps add support.

**Comment by Kyle-Kyle** [comment]
Got it.
