### ISSUE TITLE
Error running from master

### ISSUE THREAD

**Issue by asmeurer** [joerick/pyinstrument#56]
I get this error trying to run pyinstrument from master

```pytb
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/aaronmeurer/Documents/pyinstrument/pyinstrument/__main__.py", line 274, in <module>
    main()
  File "/Users/aaronmeurer/Documents/pyinstrument/pyinstrument/__main__.py", line 160, in main
    f.write(renderer.render(session))
  File "/Users/aaronmeurer/Documents/pyinstrument/pyinstrument/renderers/html.py", line 11, in render
    with io.open(os.path.join(resources_dir, 'app.js'), encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/aaronmeurer/Documents/pyinstrument/pyinstrument/renderers/html_resources/app.js'
```

Is there a file that isn't checked in, or do I need to do some kind of build?

**Comment by joerick** [comment]
Hi Aaron! Yes, there's a JS build step. The wheel has the JS compiled in, or you can build with `python setup.py build` (you'll need node/npm)

**Comment by asmeurer** [comment]
OK, I should have tried that (I tried build_ext because I know there was some talk about a C extension, but I didn't think build was separate). 

This should probably be added to the README. A better exception would help too.

**Comment by asmeurer** [comment]
By the way, I like the new HTML theme. Though I still want a way to easily navigate the sections with my arrow keys to quickly expand and collapse them https://github.com/joerick/pyinstrument/issues/11.

**Comment by joerick** [comment]
Yep, agree with both those suggestions. I'm glad you like it! Adding arrow key nav might be easier now it's got a proper JS framework behind it. Also, it would be neat to close a 4year old issue :D. PRs welcome if you've got the time!

**Comment by asmeurer** [comment]
I can PR to fix this issue. As for the arrow keys, I have no idea how to do it as I'm not a Javascript developer.

**Comment by asmeurer** [comment]
Also I didn't notice that if you omit `-o` it saves it to a temporary directory and opens it automatically. That should save me a lot of *.html files laying around in my git repos!

**Comment by asmeurer** [comment]
https://github.com/joerick/pyinstrument/pull/57
