### ISSUE TITLE
Literally just want to thank you.

### ISSUE THREAD

**Issue by Datamance** [joerick/pyinstrument#67]
What an incredible package. You clearly put a lot of care and forethought into the design, particularly w.r.t. the plug-ability with Django (which, by the way, is a HUGE lifesaver when dealing with unwieldy ORM issues!) and presentation of statistical profiling metrics. Just, wow.

A round of applause to @joerick !

**Comment by joerick** [comment]
Thank you @Datamance! Pleased it's been helpful for you. Share it with friends and colleagues! :D
