### ISSUE TITLE
Feature request: aggregating output

### ISSUE THREAD

**Issue by fvkluck** [joerick/pyinstrument#68]
First of all, thank you for writing this profiler. The visuals are nice, the information is (almost) exactly what I need, and Django integration is easy (as is using it in any other project).

However, I'm trying to get one thing to work, which I haven't been able to yet: aggregating the output data. Currently, I get a pyinstrument html file for every request that is sent to Django, but I'm also interested in the aggregation of all the requests. Is that something that can be made and would you consider accepting a pull request for this?

One possible way I think is to support pstats output, as someone requested in [this issue](https://github.com/joerick/pyinstrument/issues/64).

**Comment by joerick** [comment]
Yes I think this would be possible. I think the easiest way would be to save/load the Session objects - you could save a lot of profile sessions, and then later, load them all and concatenate the frame_records before rendering. Might be tricky to extend the command-line interface to do it, but should be possible with the Python interface! Happy to receive a PR for this :)

**Comment by danvk** [comment]
In case it helps anyone, here's a snippet to merge multiple `.pyireport` files:

```py
import functools

def merge_two_reports(a, b):
    return {
        'start_time': min(a['start_time'], b['start_time']),
        'duration': a['duration'] + b['duration'],
        'sample_count': a['sample_count'] + b['sample_count'],
        'start_call_stack': a['start_call_stack'],
        'program': a['program'],
        'cpu_time': a['cpu_time'] + b['cpu_time'],
        'frame_records': a['frame_records'] + b['frame_records'],
    }

def merge_reports(reports):
    return functools.reduce(merge_two_reports, reports)
```

**Comment by joerick** [comment]
As it happens, this feature will be included in pyinstrument 4.0! See #126 for progress! https://pyinstrument--126.org.readthedocs.build/en/126/reference.html#pyinstrument.session.Session.combine

**Comment by danvk** [comment]
Thanks @joerick! Is it possible to install a pre-release version of 4.0 via pip? I'd love to give the async support a try.

**Comment by joerick** [comment]
Sure, you can do-

    pip install git+https://github.com/joerick/pyinstrument.git@async

**Comment by ericman93** [comment]
any way to get the average of all of the requests? and maybe call count for each method?
