### ISSUE TITLE
Timeline flag -t is not recognized as keyword argument

### ISSUE THREAD

**Issue by hanaleung** [joerick/pyinstrument#69]
I'm trying to run pyinstrument with the -t flag but i'm getting this error:

pyinstrument -t -r html my_script.py

`
-packages\pyinstrument\__main__.py", line 177, in main
    renderer = renderer_class(**renderer_kwargs)
TypeError: __init__() got an unexpected keyword argument 'timeline'
`

**Comment by joerick** [comment]
Fixed in v3.1.1!
