### ISSUE TITLE
Tarball release on PyPI?

### ISSUE THREAD

**Issue by adamjstewart** [joerick/pyinstrument#77]
Hi, would it be possible to add tarball releases on PyPI? I'm trying to write a package for `pyinstrument` for the [Spack package manager](https://spack.io), but the GitHub tarball requires `npm` to install from source, and I'm having a hell of a time getting `npm` installed using Python 3. Could you add a tarball on PyPI that doesn't require `npm` to install from source?

@tgamblin

**Comment by joerick** [comment]
Hello! Yes, no problem. It's on PyPI now. The javascript bundle is pre-built (as it is in the wheel), but if you run `setup.py build` on it you will still need a working npm. If you're not using setuptools/pip to install then that shouldn't be a problem -- let me know!

**Comment by tgamblin** [comment]
Awesome!  @adamjstewart got it working and we sped some stuff up by 34x.  Thanks for pyinstrument!

**Comment by joerick** [comment]
Amazing. Glad to hear it! Thanks for letting me know. Always great to help out scientists and researchers. I think I heard you on the Changelog podcast!
