### ISSUE TITLE
Feature Request: Add support for speedscope

### ISSUE THREAD

**Issue by SqrtRyan** [joerick/pyinstrument#89]
Dear Authors,
Thank you so much for this package! It's very useful. I was hoping you could add support for speedscope like py-spy does, which is a very detailed flame chart application (hosted on https://www.speedscope.app/)

**Comment by joerick** [comment]
That would be cool. We'd need to write a new renderer that outputs the speedscope JSON format.  Should be fairly tractable. If you have time, I'd love to get a PR implementing this!
