### ISSUE TITLE
Deprecation warning due to invalid escape sequences

### ISSUE THREAD

**Issue by tirkarthi** [joerick/pyinstrument#92]
Deprecation warnings are raised due to invalid escape sequences. This can be fixed by using raw strings or escaping the literals. pyupgrade also helps in automatic conversion : https://github.com/asottile/pyupgrade/

```
find . -iname '*.py' | grep -v example | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./metrics/multi_overhead.py:16: DeprecationWarning: invalid escape sequence \.
  re.compile("[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?")
```

**Comment by joerick** [comment]
Thanks for the heads-up. Fixed in 5db1a6d6acf878cf500a448c15dd79b7787cbf01
